# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service/proto/uep_internal.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%grpc_service/proto/uep_internal.proto"\x0f\n\rHealthRequest"B\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t"&\n\x0eMetricsRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t"U\n\x0fMetricsResponse\x12\x15\n\rrequest_count\x18\x01 \x01(\x03\x12\x16\n\x0e\x61vg_latency_ms\x18\x02 \x01(\x01\x12\x13\n\x0b\x65rror_count\x18\x03 \x01(\x05\x32u\n\x12UepInternalService\x12.\n\x0bHealthCheck\x12\x0e.HealthRequest\x1a\x0f.HealthResponse\x12/\n\nGetMetrics\x12\x0f.MetricsRequest\x1a\x10.MetricsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "grpc_service.proto.uep_internal_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_HEALTHREQUEST"]._serialized_start = 41
    _globals["_HEALTHREQUEST"]._serialized_end = 56
    _globals["_HEALTHRESPONSE"]._serialized_start = 58
    _globals["_HEALTHRESPONSE"]._serialized_end = 124
    _globals["_METRICSREQUEST"]._serialized_start = 126
    _globals["_METRICSREQUEST"]._serialized_end = 164
    _globals["_METRICSRESPONSE"]._serialized_start = 166
    _globals["_METRICSRESPONSE"]._serialized_end = 251
    _globals["_UEPINTERNALSERVICE"]._serialized_start = 253
    _globals["_UEPINTERNALSERVICE"]._serialized_end = 370
# @@protoc_insertion_point(module_scope)
