# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_service.proto import (
    uep_internal_pb2 as grpc__service_dot_proto_dot_uep__internal__pb2,
)


class UepInternalServiceStub(object):
    """UEP 内部マイクロサービス間 gRPC 通信"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
            "/UepInternalService/HealthCheck",
            request_serializer=grpc__service_dot_proto_dot_uep__internal__pb2.HealthRequest.SerializeToString,
            response_deserializer=grpc__service_dot_proto_dot_uep__internal__pb2.HealthResponse.FromString,
        )
        self.GetMetrics = channel.unary_unary(
            "/UepInternalService/GetMetrics",
            request_serializer=grpc__service_dot_proto_dot_uep__internal__pb2.MetricsRequest.SerializeToString,
            response_deserializer=grpc__service_dot_proto_dot_uep__internal__pb2.MetricsResponse.FromString,
        )


class UepInternalServiceServicer(object):
    """UEP 内部マイクロサービス間 gRPC 通信"""

    def HealthCheck(self, request, context):
        """ヘルスチェック"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMetrics(self, request, context):
        """メトリクス取得"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UepInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=grpc__service_dot_proto_dot_uep__internal__pb2.HealthRequest.FromString,
            response_serializer=grpc__service_dot_proto_dot_uep__internal__pb2.HealthResponse.SerializeToString,
        ),
        "GetMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.GetMetrics,
            request_deserializer=grpc__service_dot_proto_dot_uep__internal__pb2.MetricsRequest.FromString,
            response_serializer=grpc__service_dot_proto_dot_uep__internal__pb2.MetricsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "UepInternalService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class UepInternalService(object):
    """UEP 内部マイクロサービス間 gRPC 通信"""

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/UepInternalService/HealthCheck",
            grpc__service_dot_proto_dot_uep__internal__pb2.HealthRequest.SerializeToString,
            grpc__service_dot_proto_dot_uep__internal__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/UepInternalService/GetMetrics",
            grpc__service_dot_proto_dot_uep__internal__pb2.MetricsRequest.SerializeToString,
            grpc__service_dot_proto_dot_uep__internal__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
